//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSelling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Admin_ID { get; set; }
        public string Admin_Pass { get; set; }
        public string Admin_Pass2 { get; set; }
        public string Admin_Email { get; set; }
        public Nullable<int> Admin_Role { get; set; }
        public string Admin_Token { get; set; }
        public Nullable<bool> Admin_Activate { get; set; }
        public Nullable<System.DateTime> Admin_DateCreate { get; set; }
        public Nullable<System.DateTime> Admin_DateLogin { get; set; }
        public string Admin_Name { get; set; }
    }
}
