//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSelling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int Category_ID { get; set; }
        public string Category_Name { get; set; }
        public string Category_Img { get; set; }
        public Nullable<System.DateTime> Category_DateCreate { get; set; }
        public Nullable<System.DateTime> Category_DateEdit { get; set; }
        public Nullable<bool> Category_Activate { get; set; }
    }
}
