//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSelling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Carts = new HashSet<Cart>();
            this.Comments = new HashSet<Comment>();
            this.Products = new HashSet<Product>();
            this.Replis = new HashSet<Repli>();
            this.Replis1 = new HashSet<Repli>();
        }
    
        public int User_ID { get; set; }
        public string User_LastName { get; set; }
        public string User_Name { get; set; }
        public string User_Token { get; set; }
        public Nullable<bool> User_Activate { get; set; }
        public string User_Pass { get; set; }
        public string User_Email { get; set; }
        public string User_Phone { get; set; }
        public Nullable<int> User_Role { get; set; }
        public string User_LinkF { get; set; }
        public string User_Img { get; set; }
        public Nullable<System.DateTime> User_DateCreate { get; set; }
        public Nullable<System.DateTime> User_DateLogin { get; set; }
        public Nullable<System.DateTime> User_DateBirth { get; set; }
        public Nullable<int> User_Sex { get; set; }
        public string User_Address { get; set; }
        public string User_Province { get; set; }
        public string User_City { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repli> Replis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repli> Replis1 { get; set; }
    }
}
