//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSelling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View
    {
        public int View_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<System.DateTime> View_Date { get; set; }
        public Nullable<bool> View_Bin { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
